# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Build & Run Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Run Tests
      run: xcodebuild test -scheme LayoutUIKit -destination 'platform=iOS Simulator,OS=18.1,name=iPhone 16'
